services:
  db:
      image:postgres:lastest
      container_name:69-s3-db
      ports:
        - 54321:5432
      environment:
        - POSTGRES_PASSWORD=REDACTED
        - POSTGRES_USER=administrator
        - POSTGRES_DB=KrissakornP
